squid:
  build: ./
  container_name: squid
  ports:
    - "3128:3128"
  volumes:
    - ./cache:/var/spool/squid
    - ./squid.conf:/etc/squid/squid.conf
    - ./passwords:/etc/squid/passwords
  restart: always

